---
ansible_downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
# TODO: Update Terminal config
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/tgallacher/dotfiles.git
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles-sync
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - awscli
  - coreutils
  - curl
  - moreutils
  - findutils
  - git
  - git-secrets
  - bash-completion
  - direnv
  - dwdiff
  - gifsicle
  - git
  - go
  - { name: gnu-sed, install_options: "with-default-names" }
  - gnupg
  - grep
  - httpie
  - ifstat
  - iperf
  - jq
  - nmap
  - node
  - oniguruma
  - openssh
  - openssl
  - openvpn
  - pcre2
  - popt
  - pwgen
  - python3
  - readline
  - screen
  - shared-mime-info
  - sqlite
  - ssh-copy-id
  - terraform
  - trash
  - tree
  - webp
  - { name: wget, install_options: "with-iri" }
  - wrk
  - x265
  - xz
  - { name: vim, install_options: "with-override-system-vi" }
  - yarn

homebrew_uninstalled_packages: []

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - brave-browser
  # - burp-suite
  - docker
  - docker
  - dropbox
  - evernote
  # - firefox
  - font-menlo-for-powerline
  - font-source-code-pro-for-powerline
  - google-chrome
  - handbrake
  - iterm2
  # - licecap
  - makemkv
  - nordvpn
  # Quick Look Plugins (https://github.com/sindresorhus/quick-look-plugins)
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlstephen
  - qlvideo
  - quicklook-json
  - slack
  - spotify
  - station
  # - sublime-text
  - toggl
  # - transmit
  - vagrant
  - visual-studio-code
  - vlc

homebrew_cask_uninstalled_apps: []

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# From dotfiles
osx_script: "~/.osx --no-restart"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
