---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
        - "{{ playbook_dir }}/vscode.config.yml"
      tags: ["always"]
    - name: Get current username
      shell: whoami
      changed_when: false
      register: current_username

  roles:
    - role: geerlingguy.homebrew
      tags: ["homebrew"]

    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]

    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ["mas"]

    - role: gantsign.visual-studio-code
      when: configure_vscode
      tags: ["apps"]
      users: "{{ item }}"
      with_items: "{{ vscode_config }}"

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - include_tasks: tasks/terminal.yml
      when: configure_terminal

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ["osx"]

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
