- hosts: all
  # connection: local

  # TOOD: This is a bit ugly
  vars_files:
    - defaults/dotfiles.yml
    - defaults/vscode.yml
    - defaults/main.yml
    - defaults/homebrew.yml

  pre_tasks:
    # Separate config overrides into separate `config.*.yml` files as needed.
    # Or, keep them all in a single `config.yml` file.
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config*.yml"
        - wantlist=True
      tags: ["always"]

  roles:
    - role: geerlingguy.homebrew
      when: configure_homebrew|bool
      tags: ["homebrew"]

    - role: geerlingguy.mas
      when: mas_installed_apps|bool
      tags: ["mas"]

    - role: geerlingguy.dotfiles
      when: configure_dotfiles|bool
      tags: ["dotfiles"]

    # FIXME: Figure why install extensions isn't working..
    - role: gantsign.visual-studio-code
      when: configure_vscode|bool
      tags: ["apps"]
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: "{{ visual_studio_code_settings }}"

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers|bool

    - include_tasks: tasks/terminal.yml
      when: configure_terminal

    - include_tasks: tasks/osx.yml
      when: configure_osx|bool
      tags: ["osx"]

    - include_tasks: tasks/vscode.yml
      when: configure_vscode|bool
      tags: ["apps"]
