- hosts: all

  # TOOD: This is a bit ugly
  vars_files:
    - defaults/dotfiles.yml
    - defaults/vscode.yml
    - defaults/main.yml
    - defaults/homebrew.yml
    - defaults/terminal.yml

  pre_tasks:
    # Separate config overrides into separate `config.*.yml` files as needed.
    # Or, keep them all in a single `config.yml` file.
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config*.yml"
        - wantlist=True
      tags: ["always"]

  roles:
    - role: geerlingguy.homebrew
      when: configure_homebrew|bool
      tags: ["core"]

    - role: geerlingguy.mas
      when: mas_installed_apps|bool
      tags: ["apps"]

    - role: geerlingguy.dotfiles
      when: configure_dotfiles|bool
      tags: ["core"]

    # FIXME: Figure why install extensions isn't working..
    - role: gantsign.visual-studio-code
      when: configure_vscode|bool
      tags: ["apps"]
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: "{{ visual_studio_code_settings }}"

    - role: markosamuli.nvm
      when: configure_nvm|bool
      nvm_shell_profile_scripts:
        - .nvm.zshlocal
      nvm_node_versions:
        - "{{ nvm_default_node_version }}"
        - 8.11.4

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers|bool

    - include_tasks: tasks/terminal.yml
      when: configure_terminal|bool

    - include_tasks: tasks/osx.yml
      when: configure_osx|bool

    - include_tasks: tasks/vscode.yml
      when: configure_vscode|bool
