vscode_config:
  - username: "{{ current_username }}"
    visual_studio_code_settings_overwrite: yes
    visual_studio_code_extensions:
      - AlanWalk.markdown-toc
      - alexkrechik.cucumberautocomplete
      # - annsk.alignment
      - anseki.vscode-color
      - Arjun.swagger-viewer
      - ban.spellright
      - bierner.markdown-preview-github-styles
      - CoenraadS.bracket-pair-colorizer
      - dawhite.mustache
      - dbaeumer.vscode-eslint
      - eamodio.gitlens
      - EditorConfig.EditorConfig
      - Equinusocio.vsc-community-material-theme
      - Equinusocio.vsc-material-theme
      - equinusocio.vsc-material-theme-icons
      - esbenp.prettier-vscode
      - felixfbecker.php-debug
      - felixfbecker.php-intellisense
      - felixfbecker.php-pack
      - file-icons.file-icons
      - flowtype.flow-for-vscode
      - formulahendry.auto-rename-tag
      - GrapeCity.gc-excelviewer
      - idleberg.applescript
      - ivory-lab.jenkinsfile-support
      - juanmnl.vscode-theme-1984
      - mauve.terraform
      - mgmcdermott.vscode-language-babel
      - mohsen1.prettify-json
      - ms-azuretools.vscode-docker
      - ms-python.python
      - ms-vscode.sublime-keybindings
      - ms-vscode.Theme-TomorrowKit
      - ms-vsliveshare.vsliveshare
      - msjsdiag.debugger-for-chrome
      - naumovs.color-highlight
      - Orta.vscode-jest
      - patbenatar.advanced-new-file
      - paulmolluzzo.convert-css-in-js
      - PKief.material-icon-theme
      - rebornix.ruby
      - robinbentley.sass-indented
      - sdras.night-owl
      - Shan.code-settings-sync
      - shanoor.vscode-nginx
      - silvenon.mdx
      - sleistner.vscode-fileutils
      - stkb.rewrap
      - Tyriar.sort-lines
      - vscode-icons-team.vscode-icons
      - WallabyJs.quokka-vscode
      - wayou.vscode-todo-highlight
      - wwm.better-align
      # - yo1dog.cursor-align
      - yzane.markdown-pdf
      - zhuangtongfa.material-theme
    visual_studio_code_settings:
      {
        "editor.multiCursorModifier": "ctrlCmd",
        "editor.snippetSuggestions": "top",
        "editor.formatOnPaste": false,
        "javascript.validate.enable": false,
        "workbench.startupEditor": "none",
        "editor.tabSize": 2,
        "explorer.confirmDragAndDrop": false,
        "files.trimTrailingWhitespace": true,
        "files.insertFinalNewline": true,
        "telemetry.enableTelemetry": false,
        "editor.wrappingIndent": "indent",
        "editor.showFoldingControls": "always",
        "editor.renderWhitespace": "boundary",
        "advancedNewFile.convenienceOptions": ["current", "last", "root"],
        "window.zoomLevel": 0,
        "editor.find.autoFindInSelection": true,
        "editor.find.seedSearchStringFromSelection": true,
        "editor.fontSize": 12,
        "window.openFilesInNewWindow": "off",
        "editor.scrollBeyondLastLine": false,
        "editor.wordWrap": "off",
        "workbench.colorCustomizations":
          {
            "editor.selectionBackground": "#25327a",
            "activityBarBadge.background": "#FF7042",
            "list.activeSelectionForeground": "#FF7042",
            "list.inactiveSelectionForeground": "#FF7042",
            "list.highlightForeground": "#FF7042",
            "scrollbarSlider.activeBackground": "#FF704250",
            "editorSuggestWidget.highlightForeground": "#FF7042",
            "textLink.foreground": "#FF7042",
            "progressBar.background": "#FF7042",
            "pickerGroup.foreground": "#FF7042",
            "tab.activeBorder": "#FF7042",
            "notificationLink.foreground": "#FF7042",
            "editorWidget.resizeBorder": "#FF7042",
            "editorWidget.border": "#FF7042",
            "settings.modifiedItemIndicator": "#FF7042",
            "settings.headerForeground": "#FF7042",
            "panelTitle.activeBorder": "#FF7042",
            "breadcrumb.activeSelectionForeground": "#FF7042",
            "menu.selectionForeground": "#FF7042",
            "menubar.selectionForeground": "#FF7042",
            "editor.findMatchBorder": "#FF7042",
            "selection.background": "#FF704240",
          },
        "terraform.codelens.enabled": false,
        "editor.codeLens": false,
        "flow.useNPMPackagedFlow": true,
        "window.title": "${activeEditorMedium}${separator}${rootName}",
        "workbench.editor.labelFormat": "medium",
        "eslint.validate":
          [
            { "language": "javascript", "autoFix": true },
            { "language": "javascriptreact", "autoFix": true },
            { "language": "typescript", "autoFix": true },
            { "language": "typescriptreact", "autoFix": true },
          ],
        "explorer.confirmDelete": false,
        "typescript.preferences.quoteStyle": "single",
        "editor.stablePeek": true,
        "explorer.openEditors.visible": 0,
        "editor.lightbulb.enabled": false,
        "markdown-toc.depthFrom": 2,
        "breadcrumbs.enabled": true,
        "files.eol": "\n",
        "html.format.wrapLineLength": 0,
        "eslint.alwaysShowStatus": true,
        "eslint.packageManager": "yarn",
        "extensions.ignoreRecommendations": false,
        "gitlens.advanced.telemetry.enabled": false,
        "editor.wordWrapColumn": 120,
        "materialTheme.accent": "Orange",
        "workbench.iconTheme": "material-icon-theme",
        "terminal.integrated.shell.osx": "/bin/zsh",
        "workbench.colorTheme": "Night Owl",
        "editor.renderControlCharacters": true,
        "todohighlight.isCaseSensitive": false,
        "todohighlight.defaultStyle": {},
        "editor.formatOnSave": true,
        "sync.autoUpload": true,
        "sync.removeExtensions": false,
        "sync.gist": "d96c6411c490246d322acc53d62fc759",
        "eslint.autoFixOnSave": true,
        "editor.codeActionsOnSave": { "source.fixAll.eslint": true },
      }
