---
- name: Link ansible dirs to homebrew location
  block:
  - name: Ensure Ansible downloads directory exists.
    file:
      path: "{{ ansible_downloads }}"
      state: directory

  - name: Ensure /etc/ansible directory exists.
    become: true
    file:
      path: /etc/ansible
      state: directory

  - name: Ensure /usr/local/etc directory exists.
    become: true
    file:
      path: /usr/local/etc
      state: directory

  - name: Symlink /usr/local/etc/ansible to /etc/ansible.
    become: true
    file:
      src: /etc/ansible/
      path: /usr/local/etc/ansible
      state: link
